import 'package:meals_app/models/items.dart';

List<Item> myItems = [
  Item(
    'Grilled Chicken Skewers',
    'https://www.officiallyglutenfree.com/wp-content/uploads/2022/06/Grilled-Chicken-Kabobs-11-scaled.jpg',
    Categories.grill,
    'In a bowl, mix olive oil, lemon juice, minced garlic, paprika, salt, and pepper. - Thread chicken chunks onto skewers and brush with the marinade. - Grill over medium-high heat for about 10-12 minutes, turning occasionally until fully cooked.',
    'Chicken breast or thigh, cut into chunks - Olive oil - Lemon juice - Garlic, minced - Paprika - Salt and pepper',
    false,
    0,
    true,
  ),
  Item(
    'Grilled Shrimp Tacos',
    'https://grillonadime.com/wp-content/uploads/2022/06/grilled-shrimp-tacos-8-3.jpg',
    Categories.grill,
    'Toss shrimp in taco seasoning. - Grill shrimp for 2-3 minutes per side until pink and opaque. - Serve in tortillas with coleslaw, avocado slices, and a squeeze of lime.',
    'Large shrimp, peeled and deveined - Taco seasoning - Flour tortillas - Coleslaw mix - Avocado slices - Lime wedges',
    false,
    1,
    true,
  ),
  Item(
    'Grilled Vegetable Platter',
    'https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Grilled-Vegetable-Platter_EXPS_DIYD19_42990_E07_24_7b.jpg',
    Categories.grill,
    'Brush vegetables with olive oil, balsamic vinegar, and fresh herbs. - Grill until tender and slightly charred, turning occasionally.',
    'Assorted vegetables (bell peppers, zucchini, eggplant, asparagus, etc.) - Olive oil - Balsamic vinegar - Fresh herbs (rosemary, thyme) - Salt and pepper',
    false,
    2,
    true,
  ),
  Item(
    'Grilled Portobello Mushrooms with Balsamic Glaze',
    'https://www.goodlifeeats.com/wp-content/uploads/2022/10/Balsamic-and-Thyme-Roasted-Portobello-Mushrooms-720x540.jpg',
    Categories.grill,
    'Brush mushrooms with olive oil and balsamic vinegar. - Sprinkle with minced garlic, thyme, salt, and pepper. - Grill for about 4-5 minutes per side until tender. - Drizzle with more balsamic glaze before serving.',
    'Portobello mushrooms - Olive oil - Balsamic vinegar - Garlic, minced - Fresh thyme leaves - Salt and pepper',
    false,
    3,
    true,
  ),
  Item(
    'Grilled Salmon with Dill Sauce',
    'https://img.taste.com.au/0kPJ2Qbx/taste/2016/11/bbq-salmon-with-dill-caper-sauce-89201-1.jpeg',
    Categories.grill,
    'Brush salmon with olive oil and lemon juice. - Season with fresh dill, salt, and pepper. - Grill for about 4-5 minutes per side until salmon flakes easily.',
    'Salmon fillets - Olive oil - Lemon juice - Fresh dill, chopped - Salt and pepper',
    false,
    4,
    true,
  ),
  Item(
    'Grilled Corn on the Cob with Chili Lime Butter',
    'https://www.eatwell101.com/wp-content/uploads/2017/08/grilled-corn-recipe.jpg',
    Categories.grill,
    'Carefully peel back the corn husks, remove silk, and then pull the husks back up. - Grill for 15-20 minutes, turning occasionally. - Combine softened butter, lime zest, chili powder, and salt. Spread on grilled corn.',
    'Corn on the cob, in husks - Butter, softened - Lime zest - Chili powder - Salt',
    false,
    5,
    true,
  ),
  Item(
    'Grilled Tofu and Vegetable Skewers',
    'https://www.thespruceeats.com/thmb/OwNcQJYCzFnsF52h9SND0ubCtd0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/vegan-tofu-and-vegetable-skewers-recipe-3378372-hero-03-58e4a18ebc2645229d86995b7bc912fc.jpg',
    Categories.grill,
    'Marinate tofu and vegetables in the soy sauce, garlic, ginger, and sesame oil mixture. - Thread onto skewers and grill for 10-12 minutes, turning occasionally.',
    'Firm tofu, cubed - Assorted vegetables (bell peppers, cherry tomatoes, mushrooms, onions, etc.) - Marinade: soy sauce, garlic, ginger, sesame oil',
    false,
    6,
    true,
  ),
  Item(
    'Grilled Romaine Hearts with Caesar Dressing',
    'https://minimalistbaker.com/wp-content/uploads/2019/06/Grilled-Romaine-Salad-SQUARE.jpg',
    Categories.grill,
    'Brush romaine lettuce with olive oil. - Grill for 2-3 minutes per side until slightly charred. - Drizzle with Caesar dressing and sprinkle with Parmesan cheese.',
    'Romaine lettuce hearts, halved lengthwise - Olive oil - Caesar dressing - Parmesan cheese, grated',
    false,
    7,
    true,
  ),
  Item(
    'Grilled Steak Fajitas',
    'https://playswellwithbutter.com/wp-content/uploads/2022/07/Grilled-Skirt-Steak-Fajitas-6.jpg',
    Categories.grill,
    'Toss steak with fajita seasoning. - Grill steak, bell peppers, and onions until steak is cooked to your liking and vegetables are tender. - Serve in tortillas with optional toppings.',
    'Steak strips (flank steak or skirt steak) - Fajita seasoning - Bell peppers, sliced - Onion, sliced - Flour tortillas - Salsa, sour cream, guacamole (optional)',
    false,
    8,
    true,
  ),
  Item(
    'Grilled Swordfish with Lemon Herb Butter',
    'https://whatshouldimakefor.com/wp-content/uploads/2017/06/Grilled-Swordfish-with-Herb-Butter-6-2.jpg',
    Categories.grill,
    'Preheat your grill to medium-high heat. - While the grill is heating up, prepare the swordfish steaks. Brush both sides of each steak with olive oil and season them with salt and black pepper. - In a small mixing bowl, prepare the Lemon Herb Butter. Combine the softened butter with lemon zest, lemon juice, finely chopped parsley, minced garlic, salt, and black pepper. Mix until all the ingredients are well incorporated. Set the butter aside. - Place the swordfish steaks on the hot grill. Grill them for approximately 4-5 minutes per side, or until the fish is opaque and easily flakes with a fork. Be careful not to overcook the swordfish, as it can become dry. - During the last minute of grilling, place a generous dollop of the Lemon Herb Butter on each swordfish steak, allowing it to melt and coat the fish. - Carefully remove the grilled swordfish steaks from the grill and transfer them to serving plates. - Serve the grilled swordfish hot, with any remaining Lemon Herb Butter drizzled over the top. - This dishpairs wonderfully with steamed vegetables or a light salad for a fresh and flavorful meal. - Enjoy your Grilled Swordfish with Lemon Herb Butter, a delightful and sophisticated seafood dish!',
    '4 swordfish steaks (6-8 ounces each) - Olive oil - Salt and black pepper - 1/2 cup unsalted butter, softened - Zest of 1 lemon - Juice of 1 lemon - 2 tablespoons fresh parsley, finely chopped - 2 cloves garlic, minced - Salt and black pepper to taste',
    false,
    9,
    true,
  ),
];
