import 'package:meals_app/models/items.dart';

List<Item> myItems = [
  Item(
    'Grilled Chicken Skewers',
    'https://www.officiallyglutenfree.com/wp-content/uploads/2022/06/Grilled-Chicken-Kabobs-11-scaled.jpg',
    Categories.grill,
    'In a bowl, mix olive oil, lemon juice, minced garlic, paprika, salt, and pepper. - Thread chicken chunks onto skewers and brush with the marinade. - Grill over medium-high heat for about 10-12 minutes, turning occasionally until fully cooked.',
    'Chicken breast or thigh, cut into chunks - Olive oil - Lemon juice - Garlic, minced - Paprika - Salt and pepper',
    false,
    0,
    true,
  ),
  Item(
    'Grilled Shrimp Tacos',
    'https://grillonadime.com/wp-content/uploads/2022/06/grilled-shrimp-tacos-8-3.jpg',
    Categories.grill,
    'Toss shrimp in taco seasoning. - Grill shrimp for 2-3 minutes per side until pink and opaque. - Serve in tortillas with coleslaw, avocado slices, and a squeeze of lime.',
    'Large shrimp, peeled and deveined - Taco seasoning - Flour tortillas - Coleslaw mix - Avocado slices - Lime wedges',
    false,
    1,
    true,
  ),
  Item(
    'Grilled Vegetable Platter',
    'https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Grilled-Vegetable-Platter_EXPS_DIYD19_42990_E07_24_7b.jpg',
    Categories.grill,
    'Brush vegetables with olive oil, balsamic vinegar, and fresh herbs. - Grill until tender and slightly charred, turning occasionally.',
    'Assorted vegetables (bell peppers, zucchini, eggplant, asparagus, etc.) - Olive oil - Balsamic vinegar - Fresh herbs (rosemary, thyme) - Salt and pepper',
    false,
    2,
    true,
  ),
  Item(
    'Grilled Portobello Mushrooms with Balsamic Glaze',
    'https://www.goodlifeeats.com/wp-content/uploads/2022/10/Balsamic-and-Thyme-Roasted-Portobello-Mushrooms-720x540.jpg',
    Categories.grill,
    'Brush mushrooms with olive oil and balsamic vinegar. - Sprinkle with minced garlic, thyme, salt, and pepper. - Grill for about 4-5 minutes per side until tender. - Drizzle with more balsamic glaze before serving.',
    'Portobello mushrooms - Olive oil - Balsamic vinegar - Garlic, minced - Fresh thyme leaves - Salt and pepper',
    false,
    3,
    true,
  ),
  Item(
    'Grilled Salmon with Dill Sauce',
    'https://img.taste.com.au/0kPJ2Qbx/taste/2016/11/bbq-salmon-with-dill-caper-sauce-89201-1.jpeg',
    Categories.grill,
    'Brush salmon with olive oil and lemon juice. - Season with fresh dill, salt, and pepper. - Grill for about 4-5 minutes per side until salmon flakes easily.',
    'Salmon fillets - Olive oil - Lemon juice - Fresh dill, chopped - Salt and pepper',
    false,
    4,
    true,
  ),
  Item(
    'Grilled Corn on the Cob with Chili Lime Butter',
    'https://www.eatwell101.com/wp-content/uploads/2017/08/grilled-corn-recipe.jpg',
    Categories.grill,
    'Carefully peel back the corn husks, remove silk, and then pull the husks back up. - Grill for 15-20 minutes, turning occasionally. - Combine softened butter, lime zest, chili powder, and salt. Spread on grilled corn.',
    'Corn on the cob, in husks - Butter, softened - Lime zest - Chili powder - Salt',
    false,
    5,
    true,
  ),
  Item(
    'Grilled Tofu and Vegetable Skewers',
    'https://www.thespruceeats.com/thmb/OwNcQJYCzFnsF52h9SND0ubCtd0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/vegan-tofu-and-vegetable-skewers-recipe-3378372-hero-03-58e4a18ebc2645229d86995b7bc912fc.jpg',
    Categories.grill,
    'Marinate tofu and vegetables in the soy sauce, garlic, ginger, and sesame oil mixture. - Thread onto skewers and grill for 10-12 minutes, turning occasionally.',
    'Firm tofu, cubed - Assorted vegetables (bell peppers, cherry tomatoes, mushrooms, onions, etc.) - Marinade: soy sauce, garlic, ginger, sesame oil',
    false,
    6,
    true,
  ),
  Item(
    'Grilled Romaine Hearts with Caesar Dressing',
    'https://minimalistbaker.com/wp-content/uploads/2019/06/Grilled-Romaine-Salad-SQUARE.jpg',
    Categories.grill,
    'Brush romaine lettuce with olive oil. - Grill for 2-3 minutes per side until slightly charred. - Drizzle with Caesar dressing and sprinkle with Parmesan cheese.',
    'Romaine lettuce hearts, halved lengthwise - Olive oil - Caesar dressing - Parmesan cheese, grated',
    false,
    7,
    true,
  ),
  Item(
    'Grilled Steak Fajitas',
    'https://playswellwithbutter.com/wp-content/uploads/2022/07/Grilled-Skirt-Steak-Fajitas-6.jpg',
    Categories.grill,
    'Toss steak with fajita seasoning. - Grill steak, bell peppers, and onions until steak is cooked to your liking and vegetables are tender. - Serve in tortillas with optional toppings.',
    'Steak strips (flank steak or skirt steak) - Fajita seasoning - Bell peppers, sliced - Onion, sliced - Flour tortillas - Salsa, sour cream, guacamole (optional)',
    false,
    8,
    true,
  ),
  Item(
    'Grilled Swordfish with Lemon Herb Butter',
    'https://whatshouldimakefor.com/wp-content/uploads/2017/06/Grilled-Swordfish-with-Herb-Butter-6-2.jpg',
    Categories.grill,
    'Preheat your grill to medium-high heat. - While the grill is heating up, prepare the swordfish steaks. Brush both sides of each steak with olive oil and season them with salt and black pepper. - In a small mixing bowl, prepare the Lemon Herb Butter. Combine the softened butter with lemon zest, lemon juice, finely chopped parsley, minced garlic, salt, and black pepper. Mix until all the ingredients are well incorporated. Set the butter aside. - Place the swordfish steaks on the hot grill. Grill them for approximately 4-5 minutes per side, or until the fish is opaque and easily flakes with a fork. Be careful not to overcook the swordfish, as it can become dry. - During the last minute of grilling, place a generous dollop of the Lemon Herb Butter on each swordfish steak, allowing it to melt and coat the fish. - Carefully remove the grilled swordfish steaks from the grill and transfer them to serving plates. - Serve the grilled swordfish hot, with any remaining Lemon Herb Butter drizzled over the top. - This dishpairs wonderfully with steamed vegetables or a light salad for a fresh and flavorful meal. - Enjoy your Grilled Swordfish with Lemon Herb Butter, a delightful and sophisticated seafood dish!',
    '4 swordfish steaks (6-8 ounces each) - Olive oil - Salt and black pepper - 1/2 cup unsalted butter, softened - Zest of 1 lemon - Juice of 1 lemon - 2 tablespoons fresh parsley, finely chopped - 2 cloves garlic, minced - Salt and black pepper to taste',
    false,
    9,
    true,
  ),
  Item(
    'Hamburger',
    'https://assets.epicurious.com/photos/57c5c6d9cf9e9ad43de2d96e/master/w_1000,h_684,c_limit/the-ultimate-hamburger.jpg',
    Categories.fastfood,
    'Preheat a grill or skillet over medium-high heat. - Form the ground beef into patties, season with salt and pepper. - Cook the patties for about 3-4 minutes per side, or until desired doneness. - Toast the hamburger buns on the grill for a minute or two. - Assemble the hamburger with lettuce, tomato, onion, pickles, cheese, and condiments as desired.',
    'Ground beef (80/20 lean-to-fat ratio) - Hamburger buns - Lettuce - Tomato slices - Onion slices - Pickles - Cheese slices (optional) - Ketchup and mustard (optional)',
    false,
    10,
    true,
  ),
  Item(
    'Chicken Nuggets',
    'https://images.themodernproper.com/billowy-turkey/production/posts/2023/ChickenNuggets_4.jpg?w=960&h=720&q=82&fm=jpg&fit=crop&dm=1680649269&s=a065c78be300f3a2f5c7541e3e5d606d',
    Categories.fastfood,
    'Cut the chicken into bite-sized pieces. - Season the chicken with salt and pepper. - Dredge the chicken in flour, dip in beaten eggs, and coat with breadcrumbs. - Heat oil in a deep fryer or skillet to 350°F (175°C). - Fry the chicken nuggets for 3-4 minutes until golden brown and cooked through.',
    'Boneless chicken breast or chicken tenders - All-purpose flour - Eggs - Bread crumbs - Salt and pepper',
    false,
    11,
    true,
  ),
  Item(
    'Cheese Pizza',
    'https://hips.hearstapps.com/hmg-prod/images/classic-cheese-pizza-recipe-2-64429a0cb408b.jpg?crop=0.8888888888888888xw:1xh;center,top&resize=1200:*',
    Categories.fastfood,
    'Preheat your oven to 475°F (245°C) and place a pizza stone or baking sheet inside to heat. - Roll out the pizza dough into your desired shape. - Spread pizza sauce evenly on the dough. - Sprinkle mozzarella cheese over the sauce and add your chosen toppings. - Transfer the pizza to the hot baking surface and bake for 10-12 minutes or until the crust is golden and the cheese is bubbly.',
    'Pizza dough - Pizza sauce - Mozzarella cheese - Toppings of your choice (pepperoni, mushrooms, bell peppers, etc.)',
    false,
    12,
    true,
  ),
  Item(
    'French Fries',
    'https://images.themodernproper.com/billowy-turkey/production/posts/2022/Homemade-French-Fries_8.jpg?w=960&h=720&q=82&fm=jpg&fit=crop&dm=1662474181&s=5dd5ceda5f0fe7cad1646e5c997c32ae',
    Categories.fastfood,
    'Wash and peel the potatoes (optional). - Cut the potatoes into thin strips or your desired fry shape. - Heat vegetable oil in a deep fryer or large pot to 350°F (175°C). - Carefully add the potato slices in batches and fry until golden brown (about 3-4 minutes per batch). - Remove with a slotted spoon, drain on paper towels, and season with salt.',
    'Russet potatoes - Vegetable oil - Salt',
    false,
    13,
    true,
  ),
  Item(
    'Taco',
    'https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/FAM4QZGPWAI6ZCDL353BQPJDH4.jpg',
    Categories.fastfood,
    'In a skillet, cook the ground meat over medium heat until browned. Drain any excess fat. - Add taco seasoning and water (as per package instructions) to the meat, simmer until thickened. - Warm the taco shells in the oven according to the package instructions. - Fill each taco shell with the seasoned meat, lettuce, tomatoes, cheese, sour cream, and salsa.',
    'Ground beef or ground turkey - Taco seasoning - Taco shells - Lettuce - Tomatoes, diced - Shredded cheese - Sour cream - Salsa',
    false,
    14,
    true,
  ),
  Item(
    'Vegetable Stir-Fry',
    'https://assets.bonappetit.com/photos/57ae4d9a1b33404414975cfc/master/w_3151,h_2519,c_limit/summer-vegetable-stir-fry.jpg',
    Categories.vegtable,
    'Cut the vegetables into bite-sized pieces and dice the tofu or tempeh if using. - In a hot wok or large skillet, add a bit of sesame oil and sauté minced garlic and ginger until fragrant. - Add the vegetables and tofu/tempeh and stir-fry until they start to become tender. - Mix soy sauce with a little cornstarch to create a sauce and pour it over the vegetables. Continue stir-frying until the sauce thickens. - Serve hot with rice or noodles.',
    'Assorted vegetables (e.g., bell peppers, broccoli, carrots, snap peas) - Tofu or tempeh (optional) - Soy sauce - Sesame oil - Garlic - Ginger - Cornstarch',
    false,
    15,
    true,
  ),
  Item(
    'Roasted Vegetable Medley',
    'https://twohealthykitchens.com/wp-content/uploads/2021/11/Oven-Roasted-Vegetables-Medley.jpg',
    Categories.vegtable,
    'Preheat your oven to 400°F (200°C). - Cut the vegetables into uniform-sized pieces and place them on a baking sheet. - Drizzle with olive oil, sprinkle with garlic powder, rosemary or thyme, salt, and pepper. Toss to coat evenly. - Roast in the preheated oven for 25-30 minutes or until the vegetables are tender and slightly caramelized.',
    'Assorted vegetables (e.g., potatoes, carrots, zucchini, bell peppers) - Olive oil - Garlic powder - Rosemary or thyme - Salt and pepper',
    false,
    16,
    true,
  ),
  Item(
    'Caprese Salad',
    'https://static01.nyt.com/images/2023/07/25/multimedia/MC-Classic-Caprese-fpjw/MC-Classic-Caprese-fpjw-superJumbo.jpg',
    Categories.vegtable,
    'Slice the tomatoes and fresh mozzarella cheese into even slices. - Arrange the tomato, mozzarella, and basil leaves on a plate in an alternating pattern. - Drizzle with extra-virgin olive oil and balsamic vinegar if desired. - Season with salt and pepper to taste. Serve as an appetizer or side dish.',
    'Tomatoes - Fresh mozzarella cheese - Fresh basil leaves - Extra-virgin olive oil - Balsamic vinegar (optional) - Salt and pepper',
    false,
    17,
    true,
  ),
  Item(
    'Mushroom Risotto',
    'https://www.inspiredtaste.net/wp-content/uploads/2011/12/Mushroom-Risotto-Recipe-1-1200.jpg',
    Categories.vegtable,
    'Sauté diced onions and minced garlic in a large pan with olive oil and butter until translucent. - Add sliced mushrooms and cook until they release their moisture and brown. - Stir in Arborio rice and cook for a couple of minutes until it becomes translucent. - Optionally, deglaze with white wine and allow it to be absorbed. - Gradually add hot vegetable broth, stirring constantly until the rice is creamy and cooked. - Finish with grated Parmesan cheese and serve hot.',
    'Arborio rice - Mushrooms (e.g., cremini, shiitake) - Onion - Garlic - Vegetable broth - White wine (optional) - Parmesan cheese (optional) - Butter - Olive oil',
    false,
    18,
    true,
  ),
  Item(
    'Eggplant Parmesan',
    'https://www.eatingwell.com/thmb/8igrklp0Wlt9nkeNGawc9vBC9Uc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/grilled-eggplant-parmesan-2000-ce486c66cbfe43c6bdcb23f3b799191b.jpg',
    Categories.vegtable,
    'Slice the eggplant into rounds, dip them in beaten eggs, and coat with bread crumbs. - In a large skillet, heat olive oil and fry the eggplant slices until golden brown on both sides. - Preheat your oven to 350°F (175°C). - In a baking dish, layer marinara sauce, fried eggplant slices, mozzarella cheese, and Parmesan cheese. Repeat until all ingredients are used. - Bake in the oven for about 25-30 minutes until the cheese is bubbly and golden. - Garnish with fresh basil leaves before serving.',
    'Eggplant - Bread crumbs - Eggs - Marinara sauce - Mozzarella cheese - Parmesan cheese - Fresh basil leaves - Olive oil',
    false,
    19,
    true,
  ),
  Item(
    'Chocolate Chip Cookies',
    'https://images.aws.nestle.recipes/original/5b069c3ed2feea79377014f6766fcd49_Original_NTH_Chocolate_Chip_Cookie.jpg',
    Categories.swets,
    'Preheat your oven to 350°F (175°C) and line baking sheets with parchment paper. - In a mixing bowl, whisk together the flour and baking soda. - In another bowl, cream together the butter, granulated sugar, brown sugar, salt, and vanilla extract until the mixture is light and fluffy. - Add the eggs one at a time, mixing well after each addition. - Gradually add the dry ingredients to the wet ingredients and mix until just combined. - Stir in the chocolate chips. - Drop rounded tablespoons of cookie dough onto the prepared baking sheets and bake for 9-11 minutes or until the edges are golden brown. - Allow the cookies to cool on the baking sheets for a few minutes before transferring them to a wire rack to cool completely.',
    '2 1/4 cups all-purpose flour - 1/2 teaspoon baking soda - 1 cup unsalted butter, at room temperature - 1/2 cup granulated sugar - 1 cup brown sugar, packed - 1 teaspoon salt - 2 teaspoons pure vanilla extract - 2 large eggs - 2 cups semisweet chocolate chips',
    false,
    20,
    true,
  ),
  Item(
    'Classic Apple Pie',
    'https://static01.nyt.com/images/2021/11/17/dining/12bestpierex1-apple2-copy/merlin_196953993_c5026128-d31d-4605-b57a-9cbadf24ca89-threeByTwoMediumAt2X.jpg',
    Categories.swets,
    'Preheat your oven to 425°F (220°C). - Line a pie dish with one of the pie crusts. - In a large mixing bowl, combine the sliced apples, sugar, flour, cinnamon, and salt. Toss until the apples are coated. - Pour the apple mixture into the pie crust-lined dish. - Dot the top of the apples with small pieces of butter. - Place the second pie crust on top and crimp the edges to seal the pie. - Cut a few slits in the top crust to allow steam to escape. - Bake for 45-55 minutes or until the crust is golden brown and the filling is bubbling. - Allow the pie to cool before serving.',
    '2 pie crusts (store-bought or homemade) - 6 cups sliced, peeled apples (e.g., Granny Smith or Honeycrisp) - 3/4 cup granulated sugar - 2 tablespoons all-purpose flour - 1 teaspoon ground cinnamon - 1/4 teaspoon salt - 2 tablespoons butter',
    false,
    21,
    true,
  ),
  Item(
    'Chocolate Mousse',
    'https://marleysmenu.com/wp-content/uploads/2020/04/Boozy-Chocolate-Mousse-Featured-Image-1.jpg',
    Categories.swets,
    'Melt the chopped chocolate in a heatproof bowl set over a pan of simmering water (double boiler), stirring until smooth. Remove from heat and let it cool slightly. - In a separate bowl, whip the heavy cream, sugar, vanilla extract, and a pinch of salt until soft peaks form. - Gently fold the melted chocolate into the whipped cream until well combined. - Spoon the chocolate mousse into serving dishes or glasses. - Chill in the refrigerator for at least 2 hours or until set. - Garnish with whipped cream and chocolate shavings before serving, if desired.',
    '6 ounces (170g) semisweet chocolate, chopped - 2 cups heavy cream - 3 tablespoons granulated sugar - 1 teaspoon pure vanilla extract - Pinch of salt - Whipped cream and chocolate shavings for garnish (optional)',
    false,
    22,
    true,
  ),
  Item(
    'Classic Lemonade',
    'https://www.allrecipes.com/thmb/JjkIeMWbjoAqcaz7UscVRwZMNk4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20487-old-fashioned-lemonade-ddmfs-1x1-1-86f64ae40f3949ca855c283c519c9b38.jpg',
    Categories.drinks,
    'Squeeze the juice from the lemons into a pitcher, removing any seeds. - In a separate saucepan, combine the sugar and 1 cup of water. Heat over medium heat, stirring until the sugar completely dissolves to make a simple syrup. Allow it to cool. - Add the simple syrup to the lemon juice in the pitcher. - Pour in the remaining 5 cups of water and stir well. - Taste and adjust the sweetness and tartness by adding more water or sugar as needed. - Serve over ice and garnish with lemon slices.',
    '4-6 fresh lemons - 1 cup granulated sugar - 6 cups water - Ice cubes',
    false,
    23,
    true,
  ),
  Item(
    'Homemade Iced Tea',
    'https://recipes.net/wp-content/uploads/2020/04/raspberry-flavored-iced-tea-recipe.jpg',
    Categories.drinks,
    "Place the tea bags in a heatproof pitcher and pour the boiling water over them. - Let the tea steep for about 5-7 minutes, or as per the tea type's recommended steeping time. - Remove the tea bags and discard them. - If you prefer sweetened tea, add sugar to the hot tea and stir until it's fully dissolved. Adjust the sweetness to your liking. - Allow the tea to cool to room temperature, then refrigerate until chilled. - Serve over ice and garnish with lemon wedges or fresh mint leaves if desired.",
    '4-6 tea bags (black, green, or herbal) - 4 cups boiling water - 1/2 cup granulated sugar (optional, adjust to taste) - Lemon wedges or mint leaves for garnish (optional)',
    false,
    24,
    true,
  ),
  Item(
    'Strawberry Banana Smoothie',
    'https://www.simplymaderecipes.com/wp-content/uploads/2020/02/Strawberry-Banana-Smoothie-main.png',
    Categories.drinks,
    'Place the strawberries, banana, yogurt or almond milk, and honey (if using) in a blender. - Add ice cubes if you want a colder and thicker consistency. - Blend until smooth and creamy, adding more liquid if necessary to reach your desired consistency. - Taste and add extra sweetener if needed. - Pour into a glass and serve immediately.',
    '1 cup fresh or frozen strawberries - 1 ripe banana - 1 cup plain yogurt or almond milk (for a dairy-free option) - 1-2 tablespoons honey or maple syrup (optional, for added sweetness) - Ice cubes (optional)',
    false,
    25,
    true,
  ),
];
